# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EGEbot', '0003_auto_20170416_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EGEbot.Photo'),
        ),
    ]
