# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EGEbot', '0004_auto_20170416_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EGEbot.Task'),
        ),
    ]
